doc-warnings: yes
test-warnings: no
strictness: high
max-line-length: 120
uses:
    - numpy
    - pandas
    - scipy
    - msmbuilder
    - mdtraj
autodetect: yes
requirements:
    - requirements.txt
python-targets:
    - 3
